### PR TITLE
Expose collection and item details globally

### LINKED ISSUE #5: Expose other items and collections during template generation
Hello, 

I am just wondering can you guys also sync tags and collections from Zotero. Since a paper can belong to multiple collections, maybe you can make collections as a multi-select field. I am not sure if these features are provided in the zotero-sync github repo you have been using. But it would be really awesome if you could colorize papers in the graph view based on collections and article tags.

### PR DESCRIPTION
**Pull request by Wang-Zhongwei**
Closes #5

### CODE REVIEW

**Comment by Wang-Zhongwei** [comment]
Hi @frthjf,

I've submitted a pull request in response to [issue-5](https://github.com/frthjf/obsidian-zotero-sync-client/issues/5). In this update, I modified `data.super_collections` to be an array of `ZoteroCollectionItem`. To demonstrate the changes, I've included an example template in `readme.md`. Let me know if you have any questions.

**Comment by frthjf** [comment]
Hi @Wang-Zhongwei 

Thank you! It seems like some of the files got reformatted which makes it hard to see the changes. Could you make sure the file is formatted in line with the editorconfig?

**Comment by Wang-Zhongwei** [comment]
Sure, let me figure out how to do it.

**Comment by Wang-Zhongwei** [comment]
Hi @frthjf,

I've undone the formatting changes. Feel free to test it out and see if it works.

**Comment by frthjf** [comment]
Thanks! I've made a few modifications; most notably, instead of rewriting the collection data directly for every item, I expose the collection data globally so that the name can be resolved when needed. I've updated the README example accordingly. Have a look and let me know if this doesn't work for you.

**Pull request merged**
